### ISSUE TITLE
能支持QQ频道就更好了

### ISSUE THREAD

**Issue by moian98** [KafCoppelia/nonebot_plugin_morning#1]
感谢作者提供此插件！

希望早日冒着脱发的危险适配一下频道。2333

**Comment by liuzj288** [comment]
> 感谢作者提供此插件！
> 
> 希望早日冒着脱发的危险适配一下频道。2333

这不是插件适配的，可以用频道补丁

**Comment by KafCoppelia** [comment]
> > 感谢作者提供此插件！
> > 希望早日冒着脱发的危险适配一下频道。2333
> 
> 这不是插件适配的，可以用频道补丁

你这么说确实，频道适配去商店用补丁。确实不是插件的事
