### ISSUE TITLE
在其他群不生效

### ISSUE THREAD

**Issue by Arturia169** [KafCoppelia/nonebot_plugin_morning#10]
如图我在A群发了 晚安后正常记录
在B群发送机器人无回应
检查记录文件发现确实只记录了一个

![QQ截图20230403225854](https://user-images.githubusercontent.com/69199123/229549193-2fe6a74f-70f5-4e2e-96a3-688b66199d18.png)
![QQ截图20230403225903](https://user-images.githubusercontent.com/69199123/229549205-c41cb0ea-7f5e-4421-81f9-8da28ec5a956.png)
![image](https://user-images.githubusercontent.com/69199123/229550199-c48fa4db-ef51-4151-9e10-08fc5c3d0d85.png)

**Comment by KafCoppelia** [comment]
先确认一下是否是机器人在B群被禁言等类似情况，再看看响应命令时的console输出

**Comment by Arturia169** [comment]
> 先确认一下是否是机器人在B群被禁言等类似情况，再看看响应命令时的console输出

确认过了 机器人没有被禁言，在群里发送/晚安指令后台无任何提示，于是我拉了机器人创建了另外的群聊发现指令也是能正常使用，就在B群无法使用。


>就挺邪门的我把机器人从B群退群重新加入，再次使用指令就成功了。
