### ISSUE TITLE
在早安开启的时候 报错"配置更新失败！错误原因'morning'"是什么原因 TT

### ISSUE THREAD

**Issue by KusanaGiNE** [KafCoppelia/nonebot_plugin_morning#3]
萌新求助（

**Comment by KafCoppelia** [comment]
发个错误日志截图

**Comment by KusanaGiNE** [comment]
![YL 21(V}7R(4YOXRPK_ P~J](https://user-images.githubusercontent.com/106016378/169694306-ae055e72-ca05-4cc6-8687-88f9675f5a32.png)

bot.py中没有报错
![N2{H6}MRUYQ2DQG8(XK}D$5](https://user-images.githubusercontent.com/106016378/169694384-b9f7426d-e089-4c3f-953e-73365e7a7e5c.png)

**Comment by KafCoppelia** [comment]
那你输入的命令是啥

**Comment by KusanaGiNE** [comment]
早安开启 时限
早安开启 多重起床也是一样的情况

**Comment by KafCoppelia** [comment]
好像得先在这个群里晚安或者早安，有数据记录以后才能修改设置

**Comment by KusanaGiNE** [comment]
谢谢 已经解决了
