### ISSUE TITLE
现在只保留最近一次作息记录？

### ISSUE THREAD

**Issue by liuzj288** [KafCoppelia/nonebot_plugin_morning#4]
不如都存着，这样可以统计分析周作息记录？月作息记录？年作息记录？

**Comment by KafCoppelia** [comment]
这数据也太多了吧？搞个年度报告？不现实。

感觉顶多存一周的数据，看看自己这周最晚啥时候睡，睡最长的是哪天，再搞个排行榜，每周修仙王、每周作息小王子之类的……

**Comment by KafCoppelia** [comment]
`v0.3.0`新增了更多的群组/个人早晚安信息
