### ISSUE TITLE
每日睡觉/起床人数统计有误

### ISSUE THREAD

**Issue by BCMonomial** [KafCoppelia/nonebot_plugin_morning#7]
![image](https://user-images.githubusercontent.com/69715347/196568145-e9d84c9f-9fdf-4f9b-a045-21618482e80a.png)

每日起床/睡觉人数统计有误，实际上变成了累加，而非每日重置

**Comment by KafCoppelia** [comment]
🤔我今天看看代码，今早bot被冻结1天了，明天尝试修修bug……

**Comment by KafCoppelia** [comment]
是[0.3.1](https://github.com/MinatoAquaCrews/nonebot_plugin_morning/releases/tag/v0.3.1)版本吗？我看代码没有问题……

**Comment by BCMonomial** [comment]
确实是0.3.1版本，我觉得可能是旧版配置文件过渡到新版的时候出了一些问题？我晚些时候清空数据再试试吧

**Comment by BCMonomial** [comment]
![% T~8 N_(T8MFVSN}3OMI_X](https://user-images.githubusercontent.com/69715347/198908756-37283131-a8b4-454a-9bbe-54379c85f93f.png)  
确认了，不论是清空 data,json 还是使用 nb plugin install 重新安装这个bug都依然存在，每日睡觉/起床人数无限累加。  
相关配置中更改了睡觉与起床的时间限制，允许在一天的任意时刻睡觉/起床，会与这个有关系吗？

**Comment by KafCoppelia** [comment]
是不是`resource/config.json` 配置文件内的：

```json
"night": {
    "night_intime": {
      "enable": true,
```
这一项`"enable": False`了？

**Comment by BCMonomial** [comment]
是的

**Comment by KafCoppelia** [comment]
那改成`True`就好了，可以通过命令修改（参见readme）或者手动修改配置文件。`morning`配置项下的`morning_intime`也要`"enable": True`，配置项具体含义参见readme

**Comment by BCMonomial** [comment]
那在`False`的情况下不能对起床/睡觉人数进行每日计数吗？感觉还是有些微的不方便，所以会有相关的改动吗？

**Comment by KafCoppelia** [comment]
我当初设计的想法是，如果没把早/晚安`*_intime`设置打开，那么有关早/晚安的刷新就不会启动，例如，因为没规定早/晚安时间段因此不刷新每日早晚安的人数，因为都没规定在什么时间内早/晚安（我认为不能想当然的在0点做早/晚安刷新，尤其是晚安刷新，如果以0点刷新，那么如果允许22到3点晚安，则会出现0点以后晚安又是第一个晚安的情况，这个时间点确实有讨论余地）。

当然，设置有关的改动早已在`v0.3.2 dev`版里不断修改，但是我也不好说。
