### ISSUE TITLE
无法记录个人作息

### ISSUE THREAD

**Issue by VEmpYi** [KafCoppelia/nonebot_plugin_morning#8]
我是用nb命令安装的，但是在群里使用早安命令时，只是回复了我早安，使用我的作息或者群友作息查询时并未有记录。包括morning.json中也没有我的记录。是需要初始化什么么？配置文件没有动过，是原样的。
![1669261203580_edit_369582111582145](https://user-images.githubusercontent.com/53781955/203688973-e0091a12-f5ce-4b16-bfdc-5a8fdaeb8aeb.jpg)
![屏幕截图 2022-11-24 114048](https://user-images.githubusercontent.com/53781955/203688987-b3250573-f2b7-456e-a09f-103564eccf78.png)

**Comment by KafCoppelia** [comment]
需要前一晚晚安，在次日早安才会记录你的作息时间。毕竟，需要先睡觉才行😇

**Comment by VEmpYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近有事，几天后回复。请原谅。

**Comment by VEmpYi** [comment]
好滴！我当时做好想试试那个今日群友早安的记录。结果发现没有。。。多谢解答！
